version: '3.1'
services:
  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  app-server:
    build: .
    ports:
      - 5000:80
    depends_on:
      - mongo

volumes:
  mongo-data:
