if (process.argv.length != 4) {
	console.log("Give me 2 arguments.");
	throw new Error();
}

console.log(process.argv[3]);

let jwt = require('jsonwebtoken');

let keyId = process.argv[2];  // keyId generated by eg create
let secret = process.argv[3];  // this is the keySecret generated by eg credential create

let token = jwt.sign( {
    "sub": keyId, 
    "name": "Boris Rakovan",
  }, secret);

console.log(token);

//verifying JWT token.
let decoded = jwt.verify(token, secret); // Decoding JWT using keySecret 
console.dir(decoded, { depth : null ,colors : true});
