http:
  port: 8080
admin:
  port: 9876
  host: 0.0.0.0
apiEndpoints:
  api:
    host: '*'
    paths: "/ip"
serviceEndpoints:
  httpbin:
    url: https://httpbin.org
policies:
- basic-auth
- cors
- expression
- key-auth
- log
- oauth2
- proxy
- rate-limit
pipelines:
- name: default
  apiEndpoints:
  - api
  policies:
  - key-auth: []
  - proxy:
    - action:
        serviceEndpoint: httpbin
        changeOrigin: true
